/*
 * generated by Xtext 2.16.0
 */
package de.htw.activity.xtext.parser.antlr;

import com.google.inject.Inject;
import de.htw.activity.xtext.parser.antlr.internal.InternalActivityDslParser;
import de.htw.activity.xtext.services.ActivityDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ActivityDslParser extends AbstractAntlrParser {

	@Inject
	private ActivityDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalActivityDslParser createParser(XtextTokenStream stream) {
		return new InternalActivityDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Activity";
	}

	public ActivityDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ActivityDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
