/*
 * generated by Xtext 2.16.0
 */
package de.htw.activity.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ActivityDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/htw/activity/xtext/parser/antlr/internal/InternalActivityDsl.tokens");
	}
}
