/*
 * generated by Xtext 2.16.0
 */
package de.htw.activity.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractActivityDslScopeProvider extends DelegatingScopeProvider {
}
