/*
 * generated by Xtext 2.16.0
 */
package de.htw.activity.xtext.ide


/**
 * Use this class to register ide components.
 */
class ActivityDslIdeModule extends AbstractActivityDslIdeModule {
}
