/*
 * generated by Xtext 2.16.0
 */
package de.htw.activity.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import de.htw.activity.xtext.ide.contentassist.antlr.internal.InternalActivityDslParser;
import de.htw.activity.xtext.services.ActivityDslGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class ActivityDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ActivityDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ActivityDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getActivityEdgeAccess().getAlternatives(), "rule__ActivityEdge__Alternatives");
			builder.put(grammarAccess.getActivityNodeAccess().getAlternatives(), "rule__ActivityNode__Alternatives");
			builder.put(grammarAccess.getActivityGroupAccess().getAlternatives(), "rule__ActivityGroup__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getActivityAccess().getGroup(), "rule__Activity__Group__0");
			builder.put(grammarAccess.getActivityAccess().getGroup_3(), "rule__Activity__Group_3__0");
			builder.put(grammarAccess.getActivityAccess().getGroup_3_3(), "rule__Activity__Group_3_3__0");
			builder.put(grammarAccess.getActivityAccess().getGroup_4(), "rule__Activity__Group_4__0");
			builder.put(grammarAccess.getActivityAccess().getGroup_4_3(), "rule__Activity__Group_4_3__0");
			builder.put(grammarAccess.getActivityAccess().getGroup_5(), "rule__Activity__Group_5__0");
			builder.put(grammarAccess.getActivityAccess().getGroup_5_3(), "rule__Activity__Group_5_3__0");
			builder.put(grammarAccess.getActivityAccess().getGroup_6(), "rule__Activity__Group_6__0");
			builder.put(grammarAccess.getActivityAccess().getGroup_7(), "rule__Activity__Group_7__0");
			builder.put(grammarAccess.getActivityAccess().getGroup_7_3(), "rule__Activity__Group_7_3__0");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getGroup(), "rule__ActivityParameterNode__Group__0");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getGroup_4(), "rule__ActivityParameterNode__Group_4__0");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getGroup_4_3(), "rule__ActivityParameterNode__Group_4_3__0");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getGroup_5(), "rule__ActivityParameterNode__Group_5__0");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getGroup_5_3(), "rule__ActivityParameterNode__Group_5_3__0");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getGroup_6(), "rule__ActivityParameterNode__Group_6__0");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getGroup_6_3(), "rule__ActivityParameterNode__Group_6_3__0");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getGroup_7(), "rule__ActivityParameterNode__Group_7__0");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getGroup_8(), "rule__ActivityParameterNode__Group_8__0");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getGroup_8_3(), "rule__ActivityParameterNode__Group_8_3__0");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getGroup_9(), "rule__ActivityParameterNode__Group_9__0");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getGroup_9_3(), "rule__ActivityParameterNode__Group_9_3__0");
			builder.put(grammarAccess.getActivityPartitionAccess().getGroup(), "rule__ActivityPartition__Group__0");
			builder.put(grammarAccess.getActivityPartitionAccess().getGroup_4(), "rule__ActivityPartition__Group_4__0");
			builder.put(grammarAccess.getActivityPartitionAccess().getGroup_4_3(), "rule__ActivityPartition__Group_4_3__0");
			builder.put(grammarAccess.getActivityPartitionAccess().getGroup_5(), "rule__ActivityPartition__Group_5__0");
			builder.put(grammarAccess.getActivityPartitionAccess().getGroup_5_3(), "rule__ActivityPartition__Group_5_3__0");
			builder.put(grammarAccess.getActivityPartitionAccess().getGroup_6(), "rule__ActivityPartition__Group_6__0");
			builder.put(grammarAccess.getActivityPartitionAccess().getGroup_6_3(), "rule__ActivityPartition__Group_6_3__0");
			builder.put(grammarAccess.getActivityPartitionAccess().getGroup_7(), "rule__ActivityPartition__Group_7__0");
			builder.put(grammarAccess.getActivityPartitionAccess().getGroup_8(), "rule__ActivityPartition__Group_8__0");
			builder.put(grammarAccess.getActivityPartitionAccess().getGroup_8_3(), "rule__ActivityPartition__Group_8_3__0");
			builder.put(grammarAccess.getActivityPartitionAccess().getGroup_9(), "rule__ActivityPartition__Group_9__0");
			builder.put(grammarAccess.getActivityPartitionAccess().getGroup_9_3(), "rule__ActivityPartition__Group_9_3__0");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getGroup(), "rule__InterruptibleActivityRegion__Group__0");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getGroup_4(), "rule__InterruptibleActivityRegion__Group_4__0");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getGroup_4_3(), "rule__InterruptibleActivityRegion__Group_4_3__0");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getGroup_5(), "rule__InterruptibleActivityRegion__Group_5__0");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getGroup_5_3(), "rule__InterruptibleActivityRegion__Group_5_3__0");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getGroup_6(), "rule__InterruptibleActivityRegion__Group_6__0");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getGroup_6_3(), "rule__InterruptibleActivityRegion__Group_6_3__0");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getGroup_7(), "rule__InterruptibleActivityRegion__Group_7__0");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getGroup_8(), "rule__InterruptibleActivityRegion__Group_8__0");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getGroup_8_3(), "rule__InterruptibleActivityRegion__Group_8_3__0");
			builder.put(grammarAccess.getControlFlowAccess().getGroup(), "rule__ControlFlow__Group__0");
			builder.put(grammarAccess.getControlFlowAccess().getGroup_4(), "rule__ControlFlow__Group_4__0");
			builder.put(grammarAccess.getControlFlowAccess().getGroup_5(), "rule__ControlFlow__Group_5__0");
			builder.put(grammarAccess.getControlFlowAccess().getGroup_6(), "rule__ControlFlow__Group_6__0");
			builder.put(grammarAccess.getObjectFlowAccess().getGroup(), "rule__ObjectFlow__Group__0");
			builder.put(grammarAccess.getObjectFlowAccess().getGroup_4(), "rule__ObjectFlow__Group_4__0");
			builder.put(grammarAccess.getObjectFlowAccess().getGroup_5(), "rule__ObjectFlow__Group_5__0");
			builder.put(grammarAccess.getObjectFlowAccess().getGroup_6(), "rule__ObjectFlow__Group_6__0");
			builder.put(grammarAccess.getInterruptEdgeAccess().getGroup(), "rule__InterruptEdge__Group__0");
			builder.put(grammarAccess.getInterruptEdgeAccess().getGroup_4(), "rule__InterruptEdge__Group_4__0");
			builder.put(grammarAccess.getInterruptEdgeAccess().getGroup_5(), "rule__InterruptEdge__Group_5__0");
			builder.put(grammarAccess.getInterruptEdgeAccess().getGroup_6(), "rule__InterruptEdge__Group_6__0");
			builder.put(grammarAccess.getInitialNodeAccess().getGroup(), "rule__InitialNode__Group__0");
			builder.put(grammarAccess.getInitialNodeAccess().getGroup_4(), "rule__InitialNode__Group_4__0");
			builder.put(grammarAccess.getInitialNodeAccess().getGroup_5(), "rule__InitialNode__Group_5__0");
			builder.put(grammarAccess.getInitialNodeAccess().getGroup_5_3(), "rule__InitialNode__Group_5_3__0");
			builder.put(grammarAccess.getInitialNodeAccess().getGroup_6(), "rule__InitialNode__Group_6__0");
			builder.put(grammarAccess.getInitialNodeAccess().getGroup_6_3(), "rule__InitialNode__Group_6_3__0");
			builder.put(grammarAccess.getForkNodeAccess().getGroup(), "rule__ForkNode__Group__0");
			builder.put(grammarAccess.getForkNodeAccess().getGroup_4(), "rule__ForkNode__Group_4__0");
			builder.put(grammarAccess.getForkNodeAccess().getGroup_5(), "rule__ForkNode__Group_5__0");
			builder.put(grammarAccess.getForkNodeAccess().getGroup_5_3(), "rule__ForkNode__Group_5_3__0");
			builder.put(grammarAccess.getForkNodeAccess().getGroup_6(), "rule__ForkNode__Group_6__0");
			builder.put(grammarAccess.getForkNodeAccess().getGroup_6_3(), "rule__ForkNode__Group_6_3__0");
			builder.put(grammarAccess.getJoinNodeAccess().getGroup(), "rule__JoinNode__Group__0");
			builder.put(grammarAccess.getJoinNodeAccess().getGroup_4(), "rule__JoinNode__Group_4__0");
			builder.put(grammarAccess.getJoinNodeAccess().getGroup_5(), "rule__JoinNode__Group_5__0");
			builder.put(grammarAccess.getJoinNodeAccess().getGroup_5_3(), "rule__JoinNode__Group_5_3__0");
			builder.put(grammarAccess.getJoinNodeAccess().getGroup_6(), "rule__JoinNode__Group_6__0");
			builder.put(grammarAccess.getJoinNodeAccess().getGroup_6_3(), "rule__JoinNode__Group_6_3__0");
			builder.put(grammarAccess.getConnectorAccess().getGroup(), "rule__Connector__Group__0");
			builder.put(grammarAccess.getConnectorAccess().getGroup_4(), "rule__Connector__Group_4__0");
			builder.put(grammarAccess.getConnectorAccess().getGroup_5(), "rule__Connector__Group_5__0");
			builder.put(grammarAccess.getConnectorAccess().getGroup_5_3(), "rule__Connector__Group_5_3__0");
			builder.put(grammarAccess.getConnectorAccess().getGroup_6(), "rule__Connector__Group_6__0");
			builder.put(grammarAccess.getConnectorAccess().getGroup_6_3(), "rule__Connector__Group_6_3__0");
			builder.put(grammarAccess.getConnectorAccess().getGroup_7(), "rule__Connector__Group_7__0");
			builder.put(grammarAccess.getMergeNodeAccess().getGroup(), "rule__MergeNode__Group__0");
			builder.put(grammarAccess.getMergeNodeAccess().getGroup_4(), "rule__MergeNode__Group_4__0");
			builder.put(grammarAccess.getMergeNodeAccess().getGroup_5(), "rule__MergeNode__Group_5__0");
			builder.put(grammarAccess.getMergeNodeAccess().getGroup_5_3(), "rule__MergeNode__Group_5_3__0");
			builder.put(grammarAccess.getMergeNodeAccess().getGroup_6(), "rule__MergeNode__Group_6__0");
			builder.put(grammarAccess.getMergeNodeAccess().getGroup_6_3(), "rule__MergeNode__Group_6_3__0");
			builder.put(grammarAccess.getDecisionNodeAccess().getGroup(), "rule__DecisionNode__Group__0");
			builder.put(grammarAccess.getDecisionNodeAccess().getGroup_4(), "rule__DecisionNode__Group_4__0");
			builder.put(grammarAccess.getDecisionNodeAccess().getGroup_5(), "rule__DecisionNode__Group_5__0");
			builder.put(grammarAccess.getDecisionNodeAccess().getGroup_5_3(), "rule__DecisionNode__Group_5_3__0");
			builder.put(grammarAccess.getDecisionNodeAccess().getGroup_6(), "rule__DecisionNode__Group_6__0");
			builder.put(grammarAccess.getDecisionNodeAccess().getGroup_6_3(), "rule__DecisionNode__Group_6_3__0");
			builder.put(grammarAccess.getFlowFinalNodeAccess().getGroup(), "rule__FlowFinalNode__Group__0");
			builder.put(grammarAccess.getFlowFinalNodeAccess().getGroup_4(), "rule__FlowFinalNode__Group_4__0");
			builder.put(grammarAccess.getFlowFinalNodeAccess().getGroup_5(), "rule__FlowFinalNode__Group_5__0");
			builder.put(grammarAccess.getFlowFinalNodeAccess().getGroup_5_3(), "rule__FlowFinalNode__Group_5_3__0");
			builder.put(grammarAccess.getFlowFinalNodeAccess().getGroup_6(), "rule__FlowFinalNode__Group_6__0");
			builder.put(grammarAccess.getFlowFinalNodeAccess().getGroup_6_3(), "rule__FlowFinalNode__Group_6_3__0");
			builder.put(grammarAccess.getActivityFinalNodeAccess().getGroup(), "rule__ActivityFinalNode__Group__0");
			builder.put(grammarAccess.getActivityFinalNodeAccess().getGroup_4(), "rule__ActivityFinalNode__Group_4__0");
			builder.put(grammarAccess.getActivityFinalNodeAccess().getGroup_5(), "rule__ActivityFinalNode__Group_5__0");
			builder.put(grammarAccess.getActivityFinalNodeAccess().getGroup_5_3(), "rule__ActivityFinalNode__Group_5_3__0");
			builder.put(grammarAccess.getActivityFinalNodeAccess().getGroup_6(), "rule__ActivityFinalNode__Group_6__0");
			builder.put(grammarAccess.getActivityFinalNodeAccess().getGroup_6_3(), "rule__ActivityFinalNode__Group_6_3__0");
			builder.put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
			builder.put(grammarAccess.getActionAccess().getGroup_4(), "rule__Action__Group_4__0");
			builder.put(grammarAccess.getActionAccess().getGroup_5(), "rule__Action__Group_5__0");
			builder.put(grammarAccess.getActionAccess().getGroup_5_3(), "rule__Action__Group_5_3__0");
			builder.put(grammarAccess.getActionAccess().getGroup_6(), "rule__Action__Group_6__0");
			builder.put(grammarAccess.getActionAccess().getGroup_6_3(), "rule__Action__Group_6_3__0");
			builder.put(grammarAccess.getActionAccess().getGroup_7(), "rule__Action__Group_7__0");
			builder.put(grammarAccess.getActionAccess().getGroup_7_3(), "rule__Action__Group_7_3__0");
			builder.put(grammarAccess.getActionAccess().getGroup_8(), "rule__Action__Group_8__0");
			builder.put(grammarAccess.getActionAccess().getGroup_8_3(), "rule__Action__Group_8_3__0");
			builder.put(grammarAccess.getSendSignalActionAccess().getGroup(), "rule__SendSignalAction__Group__0");
			builder.put(grammarAccess.getSendSignalActionAccess().getGroup_4(), "rule__SendSignalAction__Group_4__0");
			builder.put(grammarAccess.getSendSignalActionAccess().getGroup_5(), "rule__SendSignalAction__Group_5__0");
			builder.put(grammarAccess.getSendSignalActionAccess().getGroup_5_3(), "rule__SendSignalAction__Group_5_3__0");
			builder.put(grammarAccess.getSendSignalActionAccess().getGroup_6(), "rule__SendSignalAction__Group_6__0");
			builder.put(grammarAccess.getSendSignalActionAccess().getGroup_6_3(), "rule__SendSignalAction__Group_6_3__0");
			builder.put(grammarAccess.getAcceptTimeEventActionAccess().getGroup(), "rule__AcceptTimeEventAction__Group__0");
			builder.put(grammarAccess.getAcceptTimeEventActionAccess().getGroup_4(), "rule__AcceptTimeEventAction__Group_4__0");
			builder.put(grammarAccess.getAcceptTimeEventActionAccess().getGroup_5(), "rule__AcceptTimeEventAction__Group_5__0");
			builder.put(grammarAccess.getAcceptTimeEventActionAccess().getGroup_5_3(), "rule__AcceptTimeEventAction__Group_5_3__0");
			builder.put(grammarAccess.getAcceptTimeEventActionAccess().getGroup_6(), "rule__AcceptTimeEventAction__Group_6__0");
			builder.put(grammarAccess.getAcceptTimeEventActionAccess().getGroup_6_3(), "rule__AcceptTimeEventAction__Group_6_3__0");
			builder.put(grammarAccess.getAcceptEventActionAccess().getGroup(), "rule__AcceptEventAction__Group__0");
			builder.put(grammarAccess.getAcceptEventActionAccess().getGroup_4(), "rule__AcceptEventAction__Group_4__0");
			builder.put(grammarAccess.getAcceptEventActionAccess().getGroup_5(), "rule__AcceptEventAction__Group_5__0");
			builder.put(grammarAccess.getAcceptEventActionAccess().getGroup_5_3(), "rule__AcceptEventAction__Group_5_3__0");
			builder.put(grammarAccess.getAcceptEventActionAccess().getGroup_6(), "rule__AcceptEventAction__Group_6__0");
			builder.put(grammarAccess.getAcceptEventActionAccess().getGroup_6_3(), "rule__AcceptEventAction__Group_6_3__0");
			builder.put(grammarAccess.getInputPinAccess().getGroup(), "rule__InputPin__Group__0");
			builder.put(grammarAccess.getInputPinAccess().getGroup_4(), "rule__InputPin__Group_4__0");
			builder.put(grammarAccess.getInputPinAccess().getGroup_5(), "rule__InputPin__Group_5__0");
			builder.put(grammarAccess.getInputPinAccess().getGroup_5_3(), "rule__InputPin__Group_5_3__0");
			builder.put(grammarAccess.getInputPinAccess().getGroup_6(), "rule__InputPin__Group_6__0");
			builder.put(grammarAccess.getInputPinAccess().getGroup_6_3(), "rule__InputPin__Group_6_3__0");
			builder.put(grammarAccess.getOutputPinAccess().getGroup(), "rule__OutputPin__Group__0");
			builder.put(grammarAccess.getOutputPinAccess().getGroup_4(), "rule__OutputPin__Group_4__0");
			builder.put(grammarAccess.getOutputPinAccess().getGroup_5(), "rule__OutputPin__Group_5__0");
			builder.put(grammarAccess.getOutputPinAccess().getGroup_5_3(), "rule__OutputPin__Group_5_3__0");
			builder.put(grammarAccess.getOutputPinAccess().getGroup_6(), "rule__OutputPin__Group_6__0");
			builder.put(grammarAccess.getOutputPinAccess().getGroup_6_3(), "rule__OutputPin__Group_6_3__0");
			builder.put(grammarAccess.getObjectAccess().getGroup(), "rule__Object__Group__0");
			builder.put(grammarAccess.getObjectAccess().getGroup_4(), "rule__Object__Group_4__0");
			builder.put(grammarAccess.getObjectAccess().getGroup_5(), "rule__Object__Group_5__0");
			builder.put(grammarAccess.getObjectAccess().getGroup_5_3(), "rule__Object__Group_5_3__0");
			builder.put(grammarAccess.getObjectAccess().getGroup_6(), "rule__Object__Group_6__0");
			builder.put(grammarAccess.getObjectAccess().getGroup_6_3(), "rule__Object__Group_6_3__0");
			builder.put(grammarAccess.getCentralBufferNodeAccess().getGroup(), "rule__CentralBufferNode__Group__0");
			builder.put(grammarAccess.getCentralBufferNodeAccess().getGroup_4(), "rule__CentralBufferNode__Group_4__0");
			builder.put(grammarAccess.getCentralBufferNodeAccess().getGroup_5(), "rule__CentralBufferNode__Group_5__0");
			builder.put(grammarAccess.getCentralBufferNodeAccess().getGroup_5_3(), "rule__CentralBufferNode__Group_5_3__0");
			builder.put(grammarAccess.getCentralBufferNodeAccess().getGroup_6(), "rule__CentralBufferNode__Group_6__0");
			builder.put(grammarAccess.getCentralBufferNodeAccess().getGroup_6_3(), "rule__CentralBufferNode__Group_6_3__0");
			builder.put(grammarAccess.getDataStoreNodeAccess().getGroup(), "rule__DataStoreNode__Group__0");
			builder.put(grammarAccess.getDataStoreNodeAccess().getGroup_4(), "rule__DataStoreNode__Group_4__0");
			builder.put(grammarAccess.getDataStoreNodeAccess().getGroup_5(), "rule__DataStoreNode__Group_5__0");
			builder.put(grammarAccess.getDataStoreNodeAccess().getGroup_5_3(), "rule__DataStoreNode__Group_5_3__0");
			builder.put(grammarAccess.getDataStoreNodeAccess().getGroup_6(), "rule__DataStoreNode__Group_6__0");
			builder.put(grammarAccess.getDataStoreNodeAccess().getGroup_6_3(), "rule__DataStoreNode__Group_6_3__0");
			builder.put(grammarAccess.getActivityAccess().getActivityPartionAssignment_3_2(), "rule__Activity__ActivityPartionAssignment_3_2");
			builder.put(grammarAccess.getActivityAccess().getActivityPartionAssignment_3_3_1(), "rule__Activity__ActivityPartionAssignment_3_3_1");
			builder.put(grammarAccess.getActivityAccess().getEdgesAssignment_4_2(), "rule__Activity__EdgesAssignment_4_2");
			builder.put(grammarAccess.getActivityAccess().getEdgesAssignment_4_3_1(), "rule__Activity__EdgesAssignment_4_3_1");
			builder.put(grammarAccess.getActivityAccess().getNodesAssignment_5_2(), "rule__Activity__NodesAssignment_5_2");
			builder.put(grammarAccess.getActivityAccess().getNodesAssignment_5_3_1(), "rule__Activity__NodesAssignment_5_3_1");
			builder.put(grammarAccess.getActivityAccess().getActivityparameternodeAssignment_6_1(), "rule__Activity__ActivityparameternodeAssignment_6_1");
			builder.put(grammarAccess.getActivityAccess().getActivityGroupsAssignment_7_2(), "rule__Activity__ActivityGroupsAssignment_7_2");
			builder.put(grammarAccess.getActivityAccess().getActivityGroupsAssignment_7_3_1(), "rule__Activity__ActivityGroupsAssignment_7_3_1");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getNameAssignment_2(), "rule__ActivityParameterNode__NameAssignment_2");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getActivityPartionAssignment_4_2(), "rule__ActivityParameterNode__ActivityPartionAssignment_4_2");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getActivityPartionAssignment_4_3_1(), "rule__ActivityParameterNode__ActivityPartionAssignment_4_3_1");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getEdgesAssignment_5_2(), "rule__ActivityParameterNode__EdgesAssignment_5_2");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getEdgesAssignment_5_3_1(), "rule__ActivityParameterNode__EdgesAssignment_5_3_1");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getNodesAssignment_6_2(), "rule__ActivityParameterNode__NodesAssignment_6_2");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getNodesAssignment_6_3_1(), "rule__ActivityParameterNode__NodesAssignment_6_3_1");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getActivityparameternodeAssignment_7_1(), "rule__ActivityParameterNode__ActivityparameternodeAssignment_7_1");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getActivityGroupsAssignment_8_2(), "rule__ActivityParameterNode__ActivityGroupsAssignment_8_2");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getActivityGroupsAssignment_8_3_1(), "rule__ActivityParameterNode__ActivityGroupsAssignment_8_3_1");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getInBorderAssignment_9_2(), "rule__ActivityParameterNode__InBorderAssignment_9_2");
			builder.put(grammarAccess.getActivityParameterNodeAccess().getInBorderAssignment_9_3_1(), "rule__ActivityParameterNode__InBorderAssignment_9_3_1");
			builder.put(grammarAccess.getActivityPartitionAccess().getNameAssignment_2(), "rule__ActivityPartition__NameAssignment_2");
			builder.put(grammarAccess.getActivityPartitionAccess().getActivityPartionAssignment_4_2(), "rule__ActivityPartition__ActivityPartionAssignment_4_2");
			builder.put(grammarAccess.getActivityPartitionAccess().getActivityPartionAssignment_4_3_1(), "rule__ActivityPartition__ActivityPartionAssignment_4_3_1");
			builder.put(grammarAccess.getActivityPartitionAccess().getEdgesAssignment_5_2(), "rule__ActivityPartition__EdgesAssignment_5_2");
			builder.put(grammarAccess.getActivityPartitionAccess().getEdgesAssignment_5_3_1(), "rule__ActivityPartition__EdgesAssignment_5_3_1");
			builder.put(grammarAccess.getActivityPartitionAccess().getNodesAssignment_6_2(), "rule__ActivityPartition__NodesAssignment_6_2");
			builder.put(grammarAccess.getActivityPartitionAccess().getNodesAssignment_6_3_1(), "rule__ActivityPartition__NodesAssignment_6_3_1");
			builder.put(grammarAccess.getActivityPartitionAccess().getActivityparameternodeAssignment_7_1(), "rule__ActivityPartition__ActivityparameternodeAssignment_7_1");
			builder.put(grammarAccess.getActivityPartitionAccess().getActivityGroupsAssignment_8_2(), "rule__ActivityPartition__ActivityGroupsAssignment_8_2");
			builder.put(grammarAccess.getActivityPartitionAccess().getActivityGroupsAssignment_8_3_1(), "rule__ActivityPartition__ActivityGroupsAssignment_8_3_1");
			builder.put(grammarAccess.getActivityPartitionAccess().getActivityPartionsAssignment_9_2(), "rule__ActivityPartition__ActivityPartionsAssignment_9_2");
			builder.put(grammarAccess.getActivityPartitionAccess().getActivityPartionsAssignment_9_3_1(), "rule__ActivityPartition__ActivityPartionsAssignment_9_3_1");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getNameAssignment_2(), "rule__InterruptibleActivityRegion__NameAssignment_2");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getActivityPartionAssignment_4_2(), "rule__InterruptibleActivityRegion__ActivityPartionAssignment_4_2");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getActivityPartionAssignment_4_3_1(), "rule__InterruptibleActivityRegion__ActivityPartionAssignment_4_3_1");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getEdgesAssignment_5_2(), "rule__InterruptibleActivityRegion__EdgesAssignment_5_2");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getEdgesAssignment_5_3_1(), "rule__InterruptibleActivityRegion__EdgesAssignment_5_3_1");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getNodesAssignment_6_2(), "rule__InterruptibleActivityRegion__NodesAssignment_6_2");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getNodesAssignment_6_3_1(), "rule__InterruptibleActivityRegion__NodesAssignment_6_3_1");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getActivityparameternodeAssignment_7_1(), "rule__InterruptibleActivityRegion__ActivityparameternodeAssignment_7_1");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getActivityGroupsAssignment_8_2(), "rule__InterruptibleActivityRegion__ActivityGroupsAssignment_8_2");
			builder.put(grammarAccess.getInterruptibleActivityRegionAccess().getActivityGroupsAssignment_8_3_1(), "rule__InterruptibleActivityRegion__ActivityGroupsAssignment_8_3_1");
			builder.put(grammarAccess.getControlFlowAccess().getQualifiedNameAssignment_2(), "rule__ControlFlow__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getControlFlowAccess().getNameAssignment_4_1(), "rule__ControlFlow__NameAssignment_4_1");
			builder.put(grammarAccess.getControlFlowAccess().getTargetAssignment_5_1(), "rule__ControlFlow__TargetAssignment_5_1");
			builder.put(grammarAccess.getControlFlowAccess().getSourceAssignment_6_1(), "rule__ControlFlow__SourceAssignment_6_1");
			builder.put(grammarAccess.getObjectFlowAccess().getQualifiedNameAssignment_2(), "rule__ObjectFlow__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getObjectFlowAccess().getNameAssignment_4_1(), "rule__ObjectFlow__NameAssignment_4_1");
			builder.put(grammarAccess.getObjectFlowAccess().getTargetAssignment_5_1(), "rule__ObjectFlow__TargetAssignment_5_1");
			builder.put(grammarAccess.getObjectFlowAccess().getSourceAssignment_6_1(), "rule__ObjectFlow__SourceAssignment_6_1");
			builder.put(grammarAccess.getInterruptEdgeAccess().getQualifiedNameAssignment_2(), "rule__InterruptEdge__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getInterruptEdgeAccess().getNameAssignment_4_1(), "rule__InterruptEdge__NameAssignment_4_1");
			builder.put(grammarAccess.getInterruptEdgeAccess().getTargetAssignment_5_1(), "rule__InterruptEdge__TargetAssignment_5_1");
			builder.put(grammarAccess.getInterruptEdgeAccess().getSourceAssignment_6_1(), "rule__InterruptEdge__SourceAssignment_6_1");
			builder.put(grammarAccess.getInitialNodeAccess().getQualifiedNameAssignment_2(), "rule__InitialNode__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getInitialNodeAccess().getNameAssignment_4_1(), "rule__InitialNode__NameAssignment_4_1");
			builder.put(grammarAccess.getInitialNodeAccess().getIncomingAssignment_5_2(), "rule__InitialNode__IncomingAssignment_5_2");
			builder.put(grammarAccess.getInitialNodeAccess().getIncomingAssignment_5_3_1(), "rule__InitialNode__IncomingAssignment_5_3_1");
			builder.put(grammarAccess.getInitialNodeAccess().getOutgoingAssignment_6_2(), "rule__InitialNode__OutgoingAssignment_6_2");
			builder.put(grammarAccess.getInitialNodeAccess().getOutgoingAssignment_6_3_1(), "rule__InitialNode__OutgoingAssignment_6_3_1");
			builder.put(grammarAccess.getForkNodeAccess().getQualifiedNameAssignment_2(), "rule__ForkNode__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getForkNodeAccess().getNameAssignment_4_1(), "rule__ForkNode__NameAssignment_4_1");
			builder.put(grammarAccess.getForkNodeAccess().getIncomingAssignment_5_2(), "rule__ForkNode__IncomingAssignment_5_2");
			builder.put(grammarAccess.getForkNodeAccess().getIncomingAssignment_5_3_1(), "rule__ForkNode__IncomingAssignment_5_3_1");
			builder.put(grammarAccess.getForkNodeAccess().getOutgoingAssignment_6_2(), "rule__ForkNode__OutgoingAssignment_6_2");
			builder.put(grammarAccess.getForkNodeAccess().getOutgoingAssignment_6_3_1(), "rule__ForkNode__OutgoingAssignment_6_3_1");
			builder.put(grammarAccess.getJoinNodeAccess().getQualifiedNameAssignment_2(), "rule__JoinNode__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getJoinNodeAccess().getNameAssignment_4_1(), "rule__JoinNode__NameAssignment_4_1");
			builder.put(grammarAccess.getJoinNodeAccess().getIncomingAssignment_5_2(), "rule__JoinNode__IncomingAssignment_5_2");
			builder.put(grammarAccess.getJoinNodeAccess().getIncomingAssignment_5_3_1(), "rule__JoinNode__IncomingAssignment_5_3_1");
			builder.put(grammarAccess.getJoinNodeAccess().getOutgoingAssignment_6_2(), "rule__JoinNode__OutgoingAssignment_6_2");
			builder.put(grammarAccess.getJoinNodeAccess().getOutgoingAssignment_6_3_1(), "rule__JoinNode__OutgoingAssignment_6_3_1");
			builder.put(grammarAccess.getConnectorAccess().getQualifiedNameAssignment_2(), "rule__Connector__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getConnectorAccess().getNameAssignment_4_1(), "rule__Connector__NameAssignment_4_1");
			builder.put(grammarAccess.getConnectorAccess().getIncomingAssignment_5_2(), "rule__Connector__IncomingAssignment_5_2");
			builder.put(grammarAccess.getConnectorAccess().getIncomingAssignment_5_3_1(), "rule__Connector__IncomingAssignment_5_3_1");
			builder.put(grammarAccess.getConnectorAccess().getOutgoingAssignment_6_2(), "rule__Connector__OutgoingAssignment_6_2");
			builder.put(grammarAccess.getConnectorAccess().getOutgoingAssignment_6_3_1(), "rule__Connector__OutgoingAssignment_6_3_1");
			builder.put(grammarAccess.getConnectorAccess().getConnectedAssignment_7_1(), "rule__Connector__ConnectedAssignment_7_1");
			builder.put(grammarAccess.getMergeNodeAccess().getQualifiedNameAssignment_2(), "rule__MergeNode__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getMergeNodeAccess().getNameAssignment_4_1(), "rule__MergeNode__NameAssignment_4_1");
			builder.put(grammarAccess.getMergeNodeAccess().getIncomingAssignment_5_2(), "rule__MergeNode__IncomingAssignment_5_2");
			builder.put(grammarAccess.getMergeNodeAccess().getIncomingAssignment_5_3_1(), "rule__MergeNode__IncomingAssignment_5_3_1");
			builder.put(grammarAccess.getMergeNodeAccess().getOutgoingAssignment_6_2(), "rule__MergeNode__OutgoingAssignment_6_2");
			builder.put(grammarAccess.getMergeNodeAccess().getOutgoingAssignment_6_3_1(), "rule__MergeNode__OutgoingAssignment_6_3_1");
			builder.put(grammarAccess.getDecisionNodeAccess().getQualifiedNameAssignment_2(), "rule__DecisionNode__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getDecisionNodeAccess().getNameAssignment_4_1(), "rule__DecisionNode__NameAssignment_4_1");
			builder.put(grammarAccess.getDecisionNodeAccess().getIncomingAssignment_5_2(), "rule__DecisionNode__IncomingAssignment_5_2");
			builder.put(grammarAccess.getDecisionNodeAccess().getIncomingAssignment_5_3_1(), "rule__DecisionNode__IncomingAssignment_5_3_1");
			builder.put(grammarAccess.getDecisionNodeAccess().getOutgoingAssignment_6_2(), "rule__DecisionNode__OutgoingAssignment_6_2");
			builder.put(grammarAccess.getDecisionNodeAccess().getOutgoingAssignment_6_3_1(), "rule__DecisionNode__OutgoingAssignment_6_3_1");
			builder.put(grammarAccess.getFlowFinalNodeAccess().getQualifiedNameAssignment_2(), "rule__FlowFinalNode__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getFlowFinalNodeAccess().getNameAssignment_4_1(), "rule__FlowFinalNode__NameAssignment_4_1");
			builder.put(grammarAccess.getFlowFinalNodeAccess().getIncomingAssignment_5_2(), "rule__FlowFinalNode__IncomingAssignment_5_2");
			builder.put(grammarAccess.getFlowFinalNodeAccess().getIncomingAssignment_5_3_1(), "rule__FlowFinalNode__IncomingAssignment_5_3_1");
			builder.put(grammarAccess.getFlowFinalNodeAccess().getOutgoingAssignment_6_2(), "rule__FlowFinalNode__OutgoingAssignment_6_2");
			builder.put(grammarAccess.getFlowFinalNodeAccess().getOutgoingAssignment_6_3_1(), "rule__FlowFinalNode__OutgoingAssignment_6_3_1");
			builder.put(grammarAccess.getActivityFinalNodeAccess().getQualifiedNameAssignment_2(), "rule__ActivityFinalNode__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getActivityFinalNodeAccess().getNameAssignment_4_1(), "rule__ActivityFinalNode__NameAssignment_4_1");
			builder.put(grammarAccess.getActivityFinalNodeAccess().getIncomingAssignment_5_2(), "rule__ActivityFinalNode__IncomingAssignment_5_2");
			builder.put(grammarAccess.getActivityFinalNodeAccess().getIncomingAssignment_5_3_1(), "rule__ActivityFinalNode__IncomingAssignment_5_3_1");
			builder.put(grammarAccess.getActivityFinalNodeAccess().getOutgoingAssignment_6_2(), "rule__ActivityFinalNode__OutgoingAssignment_6_2");
			builder.put(grammarAccess.getActivityFinalNodeAccess().getOutgoingAssignment_6_3_1(), "rule__ActivityFinalNode__OutgoingAssignment_6_3_1");
			builder.put(grammarAccess.getActionAccess().getQualifiedNameAssignment_2(), "rule__Action__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getActionAccess().getNameAssignment_4_1(), "rule__Action__NameAssignment_4_1");
			builder.put(grammarAccess.getActionAccess().getIncomingAssignment_5_2(), "rule__Action__IncomingAssignment_5_2");
			builder.put(grammarAccess.getActionAccess().getIncomingAssignment_5_3_1(), "rule__Action__IncomingAssignment_5_3_1");
			builder.put(grammarAccess.getActionAccess().getOutgoingAssignment_6_2(), "rule__Action__OutgoingAssignment_6_2");
			builder.put(grammarAccess.getActionAccess().getOutgoingAssignment_6_3_1(), "rule__Action__OutgoingAssignment_6_3_1");
			builder.put(grammarAccess.getActionAccess().getOutputAssignment_7_2(), "rule__Action__OutputAssignment_7_2");
			builder.put(grammarAccess.getActionAccess().getOutputAssignment_7_3_1(), "rule__Action__OutputAssignment_7_3_1");
			builder.put(grammarAccess.getActionAccess().getInputAssignment_8_2(), "rule__Action__InputAssignment_8_2");
			builder.put(grammarAccess.getActionAccess().getInputAssignment_8_3_1(), "rule__Action__InputAssignment_8_3_1");
			builder.put(grammarAccess.getSendSignalActionAccess().getQualifiedNameAssignment_2(), "rule__SendSignalAction__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getSendSignalActionAccess().getNameAssignment_4_1(), "rule__SendSignalAction__NameAssignment_4_1");
			builder.put(grammarAccess.getSendSignalActionAccess().getIncomingAssignment_5_2(), "rule__SendSignalAction__IncomingAssignment_5_2");
			builder.put(grammarAccess.getSendSignalActionAccess().getIncomingAssignment_5_3_1(), "rule__SendSignalAction__IncomingAssignment_5_3_1");
			builder.put(grammarAccess.getSendSignalActionAccess().getOutgoingAssignment_6_2(), "rule__SendSignalAction__OutgoingAssignment_6_2");
			builder.put(grammarAccess.getSendSignalActionAccess().getOutgoingAssignment_6_3_1(), "rule__SendSignalAction__OutgoingAssignment_6_3_1");
			builder.put(grammarAccess.getAcceptTimeEventActionAccess().getQualifiedNameAssignment_2(), "rule__AcceptTimeEventAction__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getAcceptTimeEventActionAccess().getNameAssignment_4_1(), "rule__AcceptTimeEventAction__NameAssignment_4_1");
			builder.put(grammarAccess.getAcceptTimeEventActionAccess().getIncomingAssignment_5_2(), "rule__AcceptTimeEventAction__IncomingAssignment_5_2");
			builder.put(grammarAccess.getAcceptTimeEventActionAccess().getIncomingAssignment_5_3_1(), "rule__AcceptTimeEventAction__IncomingAssignment_5_3_1");
			builder.put(grammarAccess.getAcceptTimeEventActionAccess().getOutgoingAssignment_6_2(), "rule__AcceptTimeEventAction__OutgoingAssignment_6_2");
			builder.put(grammarAccess.getAcceptTimeEventActionAccess().getOutgoingAssignment_6_3_1(), "rule__AcceptTimeEventAction__OutgoingAssignment_6_3_1");
			builder.put(grammarAccess.getAcceptEventActionAccess().getQualifiedNameAssignment_2(), "rule__AcceptEventAction__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getAcceptEventActionAccess().getNameAssignment_4_1(), "rule__AcceptEventAction__NameAssignment_4_1");
			builder.put(grammarAccess.getAcceptEventActionAccess().getIncomingAssignment_5_2(), "rule__AcceptEventAction__IncomingAssignment_5_2");
			builder.put(grammarAccess.getAcceptEventActionAccess().getIncomingAssignment_5_3_1(), "rule__AcceptEventAction__IncomingAssignment_5_3_1");
			builder.put(grammarAccess.getAcceptEventActionAccess().getOutgoingAssignment_6_2(), "rule__AcceptEventAction__OutgoingAssignment_6_2");
			builder.put(grammarAccess.getAcceptEventActionAccess().getOutgoingAssignment_6_3_1(), "rule__AcceptEventAction__OutgoingAssignment_6_3_1");
			builder.put(grammarAccess.getInputPinAccess().getQualifiedNameAssignment_2(), "rule__InputPin__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getInputPinAccess().getNameAssignment_4_1(), "rule__InputPin__NameAssignment_4_1");
			builder.put(grammarAccess.getInputPinAccess().getIncomingAssignment_5_2(), "rule__InputPin__IncomingAssignment_5_2");
			builder.put(grammarAccess.getInputPinAccess().getIncomingAssignment_5_3_1(), "rule__InputPin__IncomingAssignment_5_3_1");
			builder.put(grammarAccess.getInputPinAccess().getOutgoingAssignment_6_2(), "rule__InputPin__OutgoingAssignment_6_2");
			builder.put(grammarAccess.getInputPinAccess().getOutgoingAssignment_6_3_1(), "rule__InputPin__OutgoingAssignment_6_3_1");
			builder.put(grammarAccess.getOutputPinAccess().getQualifiedNameAssignment_2(), "rule__OutputPin__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getOutputPinAccess().getNameAssignment_4_1(), "rule__OutputPin__NameAssignment_4_1");
			builder.put(grammarAccess.getOutputPinAccess().getIncomingAssignment_5_2(), "rule__OutputPin__IncomingAssignment_5_2");
			builder.put(grammarAccess.getOutputPinAccess().getIncomingAssignment_5_3_1(), "rule__OutputPin__IncomingAssignment_5_3_1");
			builder.put(grammarAccess.getOutputPinAccess().getOutgoingAssignment_6_2(), "rule__OutputPin__OutgoingAssignment_6_2");
			builder.put(grammarAccess.getOutputPinAccess().getOutgoingAssignment_6_3_1(), "rule__OutputPin__OutgoingAssignment_6_3_1");
			builder.put(grammarAccess.getObjectAccess().getQualifiedNameAssignment_2(), "rule__Object__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getObjectAccess().getNameAssignment_4_1(), "rule__Object__NameAssignment_4_1");
			builder.put(grammarAccess.getObjectAccess().getIncomingAssignment_5_2(), "rule__Object__IncomingAssignment_5_2");
			builder.put(grammarAccess.getObjectAccess().getIncomingAssignment_5_3_1(), "rule__Object__IncomingAssignment_5_3_1");
			builder.put(grammarAccess.getObjectAccess().getOutgoingAssignment_6_2(), "rule__Object__OutgoingAssignment_6_2");
			builder.put(grammarAccess.getObjectAccess().getOutgoingAssignment_6_3_1(), "rule__Object__OutgoingAssignment_6_3_1");
			builder.put(grammarAccess.getCentralBufferNodeAccess().getQualifiedNameAssignment_2(), "rule__CentralBufferNode__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getCentralBufferNodeAccess().getNameAssignment_4_1(), "rule__CentralBufferNode__NameAssignment_4_1");
			builder.put(grammarAccess.getCentralBufferNodeAccess().getIncomingAssignment_5_2(), "rule__CentralBufferNode__IncomingAssignment_5_2");
			builder.put(grammarAccess.getCentralBufferNodeAccess().getIncomingAssignment_5_3_1(), "rule__CentralBufferNode__IncomingAssignment_5_3_1");
			builder.put(grammarAccess.getCentralBufferNodeAccess().getOutgoingAssignment_6_2(), "rule__CentralBufferNode__OutgoingAssignment_6_2");
			builder.put(grammarAccess.getCentralBufferNodeAccess().getOutgoingAssignment_6_3_1(), "rule__CentralBufferNode__OutgoingAssignment_6_3_1");
			builder.put(grammarAccess.getDataStoreNodeAccess().getQualifiedNameAssignment_2(), "rule__DataStoreNode__QualifiedNameAssignment_2");
			builder.put(grammarAccess.getDataStoreNodeAccess().getNameAssignment_4_1(), "rule__DataStoreNode__NameAssignment_4_1");
			builder.put(grammarAccess.getDataStoreNodeAccess().getIncomingAssignment_5_2(), "rule__DataStoreNode__IncomingAssignment_5_2");
			builder.put(grammarAccess.getDataStoreNodeAccess().getIncomingAssignment_5_3_1(), "rule__DataStoreNode__IncomingAssignment_5_3_1");
			builder.put(grammarAccess.getDataStoreNodeAccess().getOutgoingAssignment_6_2(), "rule__DataStoreNode__OutgoingAssignment_6_2");
			builder.put(grammarAccess.getDataStoreNodeAccess().getOutgoingAssignment_6_3_1(), "rule__DataStoreNode__OutgoingAssignment_6_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ActivityDslGrammarAccess grammarAccess;

	@Override
	protected InternalActivityDslParser createParser() {
		InternalActivityDslParser result = new InternalActivityDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ActivityDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ActivityDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
