/*
 * generated by Xtext 2.16.0
 */
package de.htw.activity.xtext.ui.tests;

import com.google.inject.Injector;
import de.htw.activity.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ActivityDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("de.htw.activity.xtext.ActivityDsl");
	}

}
